var hierarchy =
[
    [ "Aabb", "structfilament_1_1_aabb.html", null ],
    [ "View::AmbientOcclusionOptions", "structfilament_1_1_view_1_1_ambient_occlusion_options.html", null ],
    [ "Attribute", "structfilament_1_1backend_1_1_attribute.html", null ],
    [ "RenderableManager::Bone", "structfilament_1_1_renderable_manager_1_1_bone.html", null ],
    [ "Box", "classfilament_1_1_box.html", null ],
    [ "BufferDescriptor", "classfilament_1_1backend_1_1_buffer_descriptor.html", [
      [ "PixelBufferDescriptor", "classfilament_1_1backend_1_1_pixel_buffer_descriptor.html", null ]
    ] ],
    [ "IndirectLight::Builder", "classfilament_1_1_indirect_light_1_1_builder.html", null ],
    [ "RenderTarget::Builder", "classfilament_1_1_render_target_1_1_builder.html", null ],
    [ "Skybox::Builder", "classfilament_1_1_skybox_1_1_builder.html", null ],
    [ "LightManager::Builder", "classfilament_1_1_light_manager_1_1_builder.html", null ],
    [ "Stream::Builder", "classfilament_1_1_stream_1_1_builder.html", null ],
    [ "Texture::Builder", "classfilament_1_1_texture_1_1_builder.html", null ],
    [ "Material::Builder", "classfilament_1_1_material_1_1_builder.html", null ],
    [ "VertexBuffer::Builder", "classfilament_1_1_vertex_buffer_1_1_builder.html", null ],
    [ "RenderableManager::Builder", "classfilament_1_1_renderable_manager_1_1_builder.html", null ],
    [ "IndexBuffer::Builder", "classfilament_1_1_index_buffer_1_1_builder.html", null ],
    [ "Camera", "classfilament_1_1_camera.html", null ],
    [ "CircularBuffer", "classfilament_1_1backend_1_1_circular_buffer.html", null ],
    [ "Color", "classfilament_1_1_color.html", null ],
    [ "CommandBase", "classfilament_1_1backend_1_1_command_base.html", [
      [ "CommandType< void(Driver::*)(ARGS...)>::Command<... >", "classfilament_1_1backend_1_1_command_type_3_01void_07_driver_1_1_5_08_07_a_r_g_s_8_8_8_08_4_1_1_command.html", null ],
      [ "CustomCommand", "classfilament_1_1backend_1_1_custom_command.html", null ],
      [ "NoopCommand", "classfilament_1_1backend_1_1_noop_command.html", null ]
    ] ],
    [ "CommandBufferQueue", "classfilament_1_1backend_1_1_command_buffer_queue.html", null ],
    [ "CommandStream", "classfilament_1_1backend_1_1_command_stream.html", null ],
    [ "CommandType< ARGS >", "structfilament_1_1backend_1_1_command_type.html", null ],
    [ "CommandType< void(Driver::*)(ARGS...)>", "structfilament_1_1backend_1_1_command_type_3_01void_07_driver_1_1_5_08_07_a_r_g_s_8_8_8_08_4.html", null ],
    [ "ConcreteDispatcher< T >", "classfilament_1_1backend_1_1_concrete_dispatcher.html", null ],
    [ "Aabb::Corners", "structfilament_1_1_aabb_1_1_corners.html", null ],
    [ "DebugRegistry", "classfilament_1_1_debug_registry.html", null ],
    [ "Dispatcher", "classfilament_1_1backend_1_1_dispatcher.html", null ],
    [ "Driver", "classfilament_1_1backend_1_1_driver.html", null ],
    [ "View::DynamicResolutionOptions", "structfilament_1_1_view_1_1_dynamic_resolution_options.html", null ],
    [ "Engine", "classfilament_1_1_engine.html", null ],
    [ "Platform::ExternalTexture", "structfilament_1_1backend_1_1_platform_1_1_external_texture.html", null ],
    [ "FaceOffsets", "structfilament_1_1backend_1_1_face_offsets.html", null ],
    [ "Fence", "classfilament_1_1_fence.html", null ],
    [ "Platform::Fence", "structfilament_1_1backend_1_1_platform_1_1_fence.html", null ],
    [ "Frustum", "classfilament_1_1_frustum.html", null ],
    [ "HandleBase", "classfilament_1_1backend_1_1_handle_base.html", [
      [ "Handle< T >", "structfilament_1_1backend_1_1_handle.html", null ],
      [ "Handle< HwProgram >", "structfilament_1_1backend_1_1_handle.html", null ],
      [ "Handle< HwTexture >", "structfilament_1_1backend_1_1_handle.html", null ]
    ] ],
    [ "IndexBuffer", "classfilament_1_1_index_buffer.html", null ],
    [ "IndirectLight", "classfilament_1_1_indirect_light.html", null ],
    [ "RenderableManager::is_supported_index_type< T >", "structfilament_1_1_renderable_manager_1_1is__supported__index__type.html", null ],
    [ "RenderableManager::is_supported_vector_type< T >", "structfilament_1_1_renderable_manager_1_1is__supported__vector__type.html", null ],
    [ "iterator", null, [
      [ "TransformManager::children_iterator", "classfilament_1_1_transform_manager_1_1children__iterator.html", null ]
    ] ],
    [ "LightManager", "classfilament_1_1_light_manager.html", null ],
    [ "Material", "classfilament_1_1_material.html", null ],
    [ "MaterialInstance", "classfilament_1_1_material_instance.html", null ],
    [ "Material::ParameterInfo", "structfilament_1_1_material_1_1_parameter_info.html", null ],
    [ "PipelineState", "structfilament_1_1backend_1_1_pipeline_state.html", null ],
    [ "Platform", "classfilament_1_1backend_1_1_platform.html", [
      [ "DefaultPlatform", "classfilament_1_1backend_1_1_default_platform.html", [
        [ "OpenGLPlatform", "classfilament_1_1backend_1_1_open_g_l_platform.html", null ]
      ] ]
    ] ],
    [ "PolygonOffset", "structfilament_1_1backend_1_1_polygon_offset.html", null ],
    [ "Texture::PrefilterOptions", "structfilament_1_1_texture_1_1_prefilter_options.html", null ],
    [ "Program", "classfilament_1_1backend_1_1_program.html", null ],
    [ "DebugRegistry::Property", "structfilament_1_1_debug_registry_1_1_property.html", null ],
    [ "VertexBuffer::QuatTangentContext", "structfilament_1_1_vertex_buffer_1_1_quat_tangent_context.html", null ],
    [ "RasterState", "structfilament_1_1backend_1_1_raster_state.html", null ],
    [ "RenderableManager", "classfilament_1_1_renderable_manager.html", null ],
    [ "Renderer", "classfilament_1_1_renderer.html", null ],
    [ "RenderPassFlags", "structfilament_1_1backend_1_1_render_pass_flags.html", null ],
    [ "RenderPassParams", "structfilament_1_1backend_1_1_render_pass_params.html", null ],
    [ "View::RenderQuality", "structfilament_1_1_view_1_1_render_quality.html", null ],
    [ "RenderTarget", "classfilament_1_1_render_target.html", null ],
    [ "Program::Sampler", "structfilament_1_1backend_1_1_program_1_1_sampler.html", null ],
    [ "SamplerGroup::Sampler", "structfilament_1_1backend_1_1_sampler_group_1_1_sampler.html", null ],
    [ "SamplerGroup", "classfilament_1_1backend_1_1_sampler_group.html", null ],
    [ "SamplerParams", "structfilament_1_1backend_1_1_sampler_params.html", null ],
    [ "Scene", "classfilament_1_1_scene.html", null ],
    [ "LightManager::ShadowOptions", "structfilament_1_1_light_manager_1_1_shadow_options.html", null ],
    [ "Skybox", "classfilament_1_1_skybox.html", null ],
    [ "Platform::Stream", "structfilament_1_1backend_1_1_platform_1_1_stream.html", null ],
    [ "Stream", "classfilament_1_1_stream.html", null ],
    [ "Platform::SwapChain", "structfilament_1_1backend_1_1_platform_1_1_swap_chain.html", null ],
    [ "SwapChain", "classfilament_1_1_swap_chain.html", null ],
    [ "TargetBufferInfo", "classfilament_1_1backend_1_1_target_buffer_info.html", null ],
    [ "Texture", "classfilament_1_1_texture.html", null ],
    [ "TextureSampler", "classfilament_1_1_texture_sampler.html", null ],
    [ "TransformManager", "classfilament_1_1_transform_manager.html", null ],
    [ "VertexBuffer", "classfilament_1_1_vertex_buffer.html", null ],
    [ "View", "classfilament_1_1_view.html", null ],
    [ "Viewport", "structfilament_1_1backend_1_1_viewport.html", [
      [ "Viewport", "classfilament_1_1_viewport.html", null ]
    ] ]
];